export const appLogo = "//img[@alt='My Shop']"
export const loginMessage = "//p[@class='info-account']"
export const landingPageTitle = "//title[normalize-space()='My account - My Shop']"
export const landingPageImage = "//img[@class='img-responsive']"
export const contactUsLink = "//a[normalize-space()='Contact us']"
export const signOutLink = "//a[@title='Log me out']"
export const shoppingCartLink = "//a[@title='View my shopping cart']"
export const shoppingCartEmpty="//span[@class='ajax_cart_no_product']"
export const footerText = "//footer[@id='footer']//div[@class='row']"
export const socialMediaSection ="//h4[normalize-space()='Follow us']"
export const twitterLink = "//a[@href='http://www.twitter.com/prestashop']"
export const facebookLink = "//a[@href='http://www.facebook.com/prestashop']"
export const prestaBlogLink = "//a[@href='http://www.prestashop.com/blog/en/feed/']"
export const searchBox = "#search_query_top"
export const searchSubmitBtn = "//button[@name='submit_search']"
export const searchProduct = "//div[@class='product-container']"
export const listOfElements = ".product_list.row.list"
export const womenCatalogLink="//a[@title='Women']"
export const randomItem2 = "//a[normalize-space()='Printed Dress']"
export const item2AddToCart = "li[class='ajax_block_product last-in-line first-item-of-tablet-line last-item-of-mobile-line col-xs-12'] div[class='button-container col-xs-7 col-md-12']"
export const randomItem1 = "//li[@class='ajax_block_product col-xs-12 col-sm-6 col-md-4 last-item-of-tablet-line']"
export const item1AddToCart = "button[name='Submit'] span"
export const item1MoreBtn = "//li[@class='ajax_block_product last-item-of-tablet-line col-xs-12']//span[contains(text(),'More')]"
export const availabilityMsg = "//span[@id='availability_value']"
export const sizes = "#group_1"
export const proceedToCheckout = "a[title='Proceed to checkout'] span"
export const cartQuantity = "a[title='View my shopping cart'] span[class='ajax_cart_quantity']"

