export const loginPageLogo = "//img[@alt='My Shop']"
export const signIn = "a[title='Log in to your customer account']"
export const createNewActHeading  = "//h3[normalize-space()='Create an account']"
export const emailId = "#email_create"
export const createUserBtn = "button[id='SubmitCreate'] span"
export const firstName = "#customer_firstname"
export const lastName  = "#customer_lastname"
export const password = "#passwd"
export const email = "#email"
export const bDate = "#days"
export const bMonth = "#months"
export const bYear = "#years"
export const registerBtn = "button[id='submitAccount'] span"
export const successMsg = ".alert.alert-success"
export const loggedInUser = "a[title='View my customer account'] span"
export const signOutLink = "a[title='Log me out']"
export const alreadyExistError = "div[id='create_account_error'] ol li"